version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "pj01-sam-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1hsg213hvqm87"
s3_prefix = "pj01-sam-app"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
